### ISSUE TITLE
Error: getaddrinfo EAI_AGAIN sqs.eu-west-1.amazonaws.com:443

### ISSUE THREAD

**Issue by tomav** [tomav/api-hour-worker#2]
```
Receive Error { Error: getaddrinfo EAI_AGAIN sqs.eu-west-1.amazonaws.com:443
    at Object.exports._errnoException (util.js:1050:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  message: 'getaddrinfo EAI_AGAIN sqs.eu-west-1.amazonaws.com:443',
  code: 'NetworkingError',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'sqs.eu-west-1.amazonaws.com',
  host: 'sqs.eu-west-1.amazonaws.com',
  port: 443,
  region: 'eu-west-1',
  retryable: true,
  time: 2017-06-03T02:03:25.169Z }
```

**Comment by YoannBuzenet** [comment]
Hello,

Did you find a way to fix this ?

**Comment by ThangalakshmiKP** [comment]
{
    "status": "failure",
    "err_msg": "getaddrinfo EAI_AGAIN bucket_name.s3.amazonaws.com  bucket_name.s3.amazonaws.com:443",
    "status_code": 404
}
